[package]
name = "ve-shader-reflect"
version = "0.1.0"
authors = ["Robin Quint <rob2309@hotmail.de>"]
description = "Creates material bindings for the shaders"
readme = "README.md"
edition = "2021"

[dependencies]
spirv-layout = "0.3.0"
thiserror = "1.0.30"
