[package]
name = "vulkan_renderer"
version = "0.1.0"
authors = ["Michael Lohr <michael@lohr-ffb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
image = "0.23.12"
vk-shader-macros = "0.2.6"
winit = "0.24.0"

[[example]]
name = "triangle"
path = "examples/src/bin/triangle.rs"
