[package]
name = "vulkan_engine"
version = "0.1.0"
authors = ["Michael Lohr <michael@lohr-ffb.de>", "Shemnei"]
edition = "2018"

[lib]
name = "vulkan_engine"

[workspace]
members = [
    "math",
]

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
env_logger = "0.8.2"
log = "0.4.14"
thiserror = "1.0.23"
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs", version = "0.2.3" }
winit = "0.24.0"
math = { path = "math" }
image = "0.23.13"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1
