[workspace]
members = [
    "crates/engine",
    "crates/editor",
    "crates/ve_asset",
    "crates/ve_format",
    "crates/ve_shader_reflect",
]

[profile.production]
inherits = "release"
opt-level = 3
lto = "fat"
incremental = false
codegen-units = 1
