[workspace]
members = [
    "crates/engine",
    "crates/ve_asset",
    "crates/ve_format",
    "crates/ve_shader_reflect",
]

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 0
