[package]
name = "vulkan_renderer"
version = "0.1.0"
authors = ["Michael Lohr <michael@lohr-ffb.de>"]
edition = "2018"

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
vk-mem = "0.2.2"
vk-shader-macros = "0.2.6"
winit = "0.24.0"

[[example]]
name = "triangle"
path = "examples/src/bin/triangle.rs"
