[package]
name = "math"
version = "0.1.0"
authors = ["Shemnei", "Michael Lohr <michael@lohr-ffb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
