[package]
name = "crystal"
version = "0.1.1"
authors = ["Shemnei", "Michael Lohr <michael@lohr-ffb.de>", "Robin Quint <rob2309@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
